import "./src/styles/global.css"
import "fontsource-rubik/600-normal.css"
import "fontsource-rubik/400-normal.css"
import "fontsource-montserrat/600-normal.css"
import "fontsource-montserrat/400-normal.css"
